//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Bin
{
    public int ID { get; set; }
    public string ClientID { get; set; }
    public int ProductID { get; set; }
    public int Quantity { get; set; }
    public Nullable<System.DateTime> DatePurchase { get; set; }
    public bool IsInBin { get; set; }

    public virtual Product Product { get; set; }
}

public partial class FeedBack
{
    public int ID { get; set; }
    public int UserID { get; set; }
    public string FeedBack1 { get; set; }
    public bool Checked { get; set; }
    public string Comments { get; set; }
    public System.DateTime Date { get; set; }

    public virtual UserInformation UserInformation { get; set; }
}

public partial class Message
{
    public int ProductID { get; set; }
    public int UserID { get; set; }
    public string FeedBack { get; set; }
    public bool Checked { get; set; }
    public string Comments { get; set; }
    public System.DateTime Date { get; set; }
    public int ID { get; set; }

    public virtual Product Product { get; set; }
}

public partial class Product
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
        this.Bins = new HashSet<Bin>();
        this.Messages = new HashSet<Message>();
    }

    public int ProductID { get; set; }
    public int ProductTypeID { get; set; }
    public string ProductName { get; set; }
    public Nullable<double> ProductPrice { get; set; }
    public string ProductDescription { get; set; }
    public string ProductImage { get; set; }
    public int SellerID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Bin> Bins { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Message> Messages { get; set; }
    public virtual ProductType ProductType { get; set; }
    public virtual UserInformation UserInformation { get; set; }
}

public partial class ProductType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductType()
    {
        this.Products = new HashSet<Product>();
    }

    public int TypeID { get; set; }
    public string Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class UserInformation
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserInformation()
    {
        this.FeedBacks = new HashSet<FeedBack>();
        this.Products = new HashSet<Product>();
    }

    public int id { get; set; }
    public string GUID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Address { get; set; }
    public int PostalCode { get; set; }
    public Nullable<int> Phone { get; set; }
    public string EmailAddress { get; set; }
    public bool IsBlocked { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FeedBack> FeedBacks { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}
